name: Publish Python ðŸ distributions ðŸ“¦ to PyPI
on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./autorag
jobs:
  pypi-publish:
    environment: release
    name: upload release to PyPI
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: 'python -m pip install --upgrade pip

          python -m pip install setuptools wheel twine build setuptools-scm

          '
      - id: measurement-4
        name: Record Measurement After Install dependencies
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Install dependencies
          task: get-measurement
      - id: changed-files
        name: Get changed files
        uses: tj-actions/changed-files@v46
      - env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        id: version_changed
        name: Check for VERSION file change
        run: "echo \"changed=false\" >> $GITHUB_ENV\nif echo \"${ALL_CHANGED_FILES}\"\
          \ | grep -q 'VERSION'; then\n  echo \"changed=true\" >> $GITHUB_ENV\nfi\n"
      - id: measurement-7
        name: Record Measurement After Check for VERSION file change
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Check for VERSION file change
          task: get-measurement
      - if: env.changed == 'true'
        name: Build
        run: 'python -m build

          '
      - id: measurement-9
        name: Record Measurement After Build
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Build
          task: get-measurement
      - if: env.changed == 'true'
        name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: autorag/dist/
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
